### ISSUE TITLE
Custom trees

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#53]
This is a bit of a crackpot idea, but how about making tree generation customizable to some extent? I'm not sure exactly how, but there's a lot of different types of trees that generate across the world, and being able to toggle them on or off, allowing them to spawn in certain different biomes, and creating new custom tree types could pose interesting for custom world generation.

**Comment by Niko-sk2x** [comment]
This would fall under biome customization, and while it's possible to some extent, it would require the mod knowing how to construct every tree generator object in the game. Possible for vanilla, not really for modded tree generators (well, except for a big hardcoded list).

I'm going to keep it there, because it's likely I will do some tests on that.

**Comment by muzikbike** [comment]
Closing for now as CWG for 1.17 and above should have this functionality upon release; main ticket for terrain feature customisation in 1.12.2 is now #119
